-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 16:28:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seedling_shop_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `seedling_shop_db` ;

-- -----------------------------------------------------
-- Schema seedling_shop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seedling_shop_db` DEFAULT CHARACTER SET utf8 ;
USE `seedling_shop_db` ;

-- -----------------------------------------------------
-- Table `seedling_shop_db`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`table1` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`categories` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`users` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `role_id` INT NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  INDEX `fk_users_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `seedling_shop_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`countries` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`countries` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_code` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`locations` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`locations` (
  `id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loc_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_loc_countr_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_loc_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `seedling_shop_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loc_countr`
    FOREIGN KEY (`country_id`)
    REFERENCES `seedling_shop_db`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`carts` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cost` DECIMAL NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carts_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `seedling_shop_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`manufacturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`manufacturers` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`products` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(7,2) NOT NULL,
  `description` VARCHAR(80) NOT NULL,
  `category_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prod_cat_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_prod_man_idx` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_prod_cat`
    FOREIGN KEY (`category_id`)
    REFERENCES `seedling_shop_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prod_man`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `seedling_shop_db`.`manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`order_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`order_statuses` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`order_statuses` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`order` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `cost` DECIMAL(10) NOT NULL,
  `status_id` INT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `status_description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ord_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_ord_ord_stat_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_ord_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `seedling_shop_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ord_ord_stat`
    FOREIGN KEY (`status_id`)
    REFERENCES `seedling_shop_db`.`order_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`order_details` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`order_details` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `count` INT NOT NULL,
  `position_cost` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ord_det_prod_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_ord_det_ord_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_ord_det_prod`
    FOREIGN KEY (`product_id`)
    REFERENCES `seedling_shop_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ord_det_ord`
    FOREIGN KEY (`order_id`)
    REFERENCES `seedling_shop_db`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seedling_shop_db`.`cart_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seedling_shop_db`.`cart_details` ;

CREATE TABLE IF NOT EXISTS `seedling_shop_db`.`cart_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `count` INT NOT NULL,
  `position_cost` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cart_det_cart`
    FOREIGN KEY (`id`)
    REFERENCES `seedling_shop_db`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
